# Generated by Django 2.0.13 on 2021-03-14 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Omdata_65147887cf6a4237a3ae2b5584623d30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_uuid', models.UUIDField(blank=True, null=True, verbose_name='流程編號')),
                ('dataid_header', models.CharField(max_length=3, verbose_name='資料代碼')),
                ('data_no', models.IntegerField(blank=True, null=True, verbose_name='資料編號')),
                ('history', models.BooleanField(default=False, verbose_name='歷史資料')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='狀態')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='標題')),
                ('level', models.CharField(blank=True, max_length=200, null=True, verbose_name='燈號')),
                ('group', models.CharField(blank=True, max_length=500, null=True, verbose_name='受派群組')),
                ('closed', models.BooleanField(default=False, verbose_name='關閉標記')),
                ('stop_uuid', models.TextField(blank=True, null=True, verbose_name='關卡')),
                ('stop_chart_type', models.TextField(blank=True, null=True, verbose_name='關卡類型')),
                ('stop_chart_text', models.TextField(blank=True, null=True, verbose_name='關卡名稱')),
                ('running', models.BooleanField(default=False, verbose_name='執行標記')),
                ('error', models.BooleanField(default=False, verbose_name='是否異常')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('stoptime', models.DateTimeField(blank=True, null=True, verbose_name='停止時間')),
                ('data_param', models.TextField(blank=True, null=True, verbose_name='流程參數')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='錯誤訊息')),
                ('is_child', models.BooleanField(default=False, verbose_name='子單')),
                ('formitm_1', models.TextField(blank=True, null=True)),
                ('formitm_2', models.TextField(blank=True, null=True)),
                ('formitm_3', models.TextField(blank=True, null=True)),
                ('formitm_4', models.TextField(blank=True, null=True)),
                ('formitm_5', models.TextField(blank=True, null=True)),
                ('formitm_6', models.TextField(blank=True, null=True)),
                ('formitm_7', models.TextField(blank=True, null=True)),
                ('formitm_8', models.TextField(blank=True, null=True)),
                ('formitm_9', models.TextField(blank=True, null=True)),
                ('formitm_10', models.TextField(blank=True, null=True)),
                ('formitm_11', models.TextField(blank=True, null=True)),
                ('formitm_12', models.TextField(blank=True, null=True)),
                ('formitm_13', models.TextField(blank=True, null=True)),
                ('formitm_14', models.TextField(blank=True, null=True)),
                ('formitm_15', models.TextField(blank=True, null=True)),
                ('formitm_16', models.TextField(blank=True, null=True)),
                ('formitm_17', models.TextField(blank=True, null=True)),
                ('formitm_18', models.TextField(blank=True, null=True)),
                ('formitm_19', models.TextField(blank=True, null=True)),
                ('formitm_20', models.TextField(blank=True, null=True)),
                ('formitm_21', models.TextField(blank=True, null=True)),
                ('formitm_22', models.TextField(blank=True, null=True)),
                ('formitm_23', models.TextField(blank=True, null=True)),
                ('formitm_24', models.TextField(blank=True, null=True)),
                ('formitm_25', models.TextField(blank=True, null=True)),
                ('formitm_26', models.TextField(blank=True, null=True)),
                ('formitm_27', models.TextField(blank=True, null=True)),
                ('formitm_28', models.TextField(blank=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_65147887cf6a4237a3ae2b5584623d30', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='開單人員')),
                ('init_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='omformmodel.Omdata_65147887cf6a4237a3ae2b5584623d30', verbose_name='初始資料')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_65147887cf6a4237a3ae2b5584623d30', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='更新人員')),
            ],
            options={
                'permissions': (('Omdata_65147887cf6a4237a3ae2b5584623d30_Add', '新增事故管理'), ('Omdata_65147887cf6a4237a3ae2b5584623d30_Modify', '修改事故管理'), ('Omdata_65147887cf6a4237a3ae2b5584623d30_View', '檢視事故管理'), ('Omdata_65147887cf6a4237a3ae2b5584623d30_Delete', '刪除事故管理')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Omdata_65147887cf6a4237a3ae2b5584623d30_DataNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Omdata_65147887cf6a4237a3ae2b5584623d30_ValueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_uuid', models.UUIDField(blank=True, null=True, verbose_name='流程編號')),
                ('data_no', models.IntegerField(blank=True, null=True, verbose_name='資料編號')),
                ('data_id', models.IntegerField(blank=True, null=True, verbose_name='多重資料編號')),
                ('chart_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='功能點')),
                ('stop_chart_type', models.TextField(blank=True, null=True, verbose_name='關卡類型')),
                ('stop_chart_text', models.TextField(blank=True, null=True, verbose_name='關卡名稱')),
                ('input_data', models.TextField(blank=True, null=True, verbose_name='輸入參數')),
                ('output_data', models.TextField(blank=True, null=True, verbose_name='輸出參數')),
                ('error', models.BooleanField(default=False, verbose_name='異常標記')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
