# Generated by Django 3.1.5 on 2021-01-21 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omformmodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Omdata_5eb104183f3945ecab83f94e53190bbb_DataNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Omdata_5eb104183f3945ecab83f94e53190bbb_ValueHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_uuid', models.UUIDField(blank=True, null=True, verbose_name='Flow Number')),
                ('data_no', models.IntegerField(blank=True, null=True, verbose_name='Data Number')),
                ('data_id', models.IntegerField(blank=True, null=True, verbose_name='Multiple data number')),
                ('chart_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Function Point')),
                ('stop_chart_type', models.TextField(blank=True, null=True, verbose_name='Stage Type')),
                ('stop_chart_text', models.TextField(blank=True, null=True, verbose_name='Stage Name')),
                ('input_data', models.TextField(blank=True, null=True, verbose_name='Input parameters')),
                ('output_data', models.TextField(blank=True, null=True, verbose_name='Output Parameters')),
                ('error', models.BooleanField(default=False, verbose_name='Error Tag')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Omdata_5eb104183f3945ecab83f94e53190bbb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_uuid', models.UUIDField(blank=True, null=True, verbose_name='Flow Number')),
                ('dataid_header', models.CharField(max_length=3, verbose_name='Data Code')),
                ('data_no', models.IntegerField(blank=True, null=True, verbose_name='Data Number')),
                ('history', models.BooleanField(default=False, verbose_name='Historical Information')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Status')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('level', models.CharField(blank=True, max_length=200, null=True, verbose_name='Level')),
                ('group', models.CharField(blank=True, max_length=500, null=True, verbose_name='Send Group')),
                ('closed', models.BooleanField(default=False, verbose_name='Close Tag')),
                ('stop_uuid', models.TextField(blank=True, null=True, verbose_name='Stage')),
                ('stop_chart_type', models.TextField(blank=True, null=True, verbose_name='Stage Type')),
                ('stop_chart_text', models.TextField(blank=True, null=True, verbose_name='Stage Name')),
                ('running', models.BooleanField(default=False, verbose_name='Execute Tag')),
                ('error', models.BooleanField(default=False, verbose_name='Error')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('stoptime', models.DateTimeField(blank=True, null=True, verbose_name='Stop Time')),
                ('data_param', models.TextField(blank=True, null=True, verbose_name='Flow Parameters')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('is_child', models.BooleanField(default=False, verbose_name='Child Form')),
                ('formitm_1', models.TextField(blank=True, null=True)),
                ('formitm_2', models.TextField(blank=True, null=True)),
                ('formitm_3', models.TextField(blank=True, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_5eb104183f3945ecab83f94e53190bbb', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Create User')),
                ('init_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_data', to='omformmodel.omdata_5eb104183f3945ecab83f94e53190bbb', verbose_name='Initial Information')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_5eb104183f3945ecab83f94e53190bbb', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Update User')),
            ],
            options={
                'permissions': (('Omdata_5eb104183f3945ecab83f94e53190bbb_Add', 'Newdata entry'), ('Omdata_5eb104183f3945ecab83f94e53190bbb_Modify', 'Modifydata entry'), ('Omdata_5eb104183f3945ecab83f94e53190bbb_View', 'Viewdata entry'), ('Omdata_5eb104183f3945ecab83f94e53190bbb_Delete', 'Deletedata entry')),
                'default_permissions': (),
            },
        ),
    ]
