# Generated by Django 2.0.13 on 2021-03-14 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(blank=True, default=1, verbose_name='服務編號')),
                ('flow_uuid', models.UUIDField(default=uuid.uuid4, verbose_name='流程編號')),
                ('role', models.TextField(blank=True, verbose_name='允許角色')),
                ('default_value', models.TextField(blank=True, verbose_name='預設值')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OmServiceDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='服務設計')),
                ('language_package', models.TextField(default='{}', verbose_name='語言包')),
            ],
            options={
                'permissions': (('OmServiceDesign_Manage', '服務請求管理'),),
                'default_permissions': (),
            },
        ),
    ]
