# Generated by Django 3.1.5 on 2021-01-23 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omformflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspaceapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sladata',
            name='sla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omformflow.slarule'),
        ),
        migrations.AddField(
            model_name='omdataworklog',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_worklog', to=settings.AUTH_USER_MODEL, verbose_name='建立人'),
        ),
        migrations.AddField(
            model_name='omdatarelation',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='建立人員'),
        ),
        migrations.AddField(
            model_name='omdatafiles',
            name='upload_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_omdatefile', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='上傳人員'),
        ),
        migrations.AddField(
            model_name='flowworkspace',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flowworkspace',
            name='flow_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omformflow.workspaceapplication'),
        ),
        migrations.AddField(
            model_name='flowactive',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flowactive',
            name='flow_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omformflow.activeapplication'),
        ),
        migrations.AddField(
            model_name='activeapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
