# Generated by Django 3.1.5 on 2021-01-26 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omformflow', '0002_auto_20210123_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspaceapplication',
            options={'default_permissions': (), 'permissions': (('OmFormFlow_Manage', 'Customized flow Management'),)},
        ),
        migrations.AlterField(
            model_name='activeapplication',
            name='app_attr',
            field=models.CharField(max_length=100, verbose_name='Properties'),
        ),
        migrations.AlterField(
            model_name='activeapplication',
            name='language_package',
            field=models.TextField(default='{}', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='activeapplication',
            name='undeploy_flag',
            field=models.BooleanField(default=False, verbose_name='Offline'),
        ),
        migrations.AlterField(
            model_name='activeapplication',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='activeapplication',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Flow Version'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='action1',
            field=models.TextField(blank=True, null=True, verbose_name='Quick Operation 1'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='action2',
            field=models.TextField(blank=True, null=True, verbose_name='Quick Operation 2'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='api',
            field=models.BooleanField(default=False, verbose_name='API'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='api_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='API_path'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='attachment',
            field=models.BooleanField(default=False, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='attr',
            field=models.TextField(blank=True, null=True, verbose_name='Properties'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='common',
            field=models.BooleanField(default=False, verbose_name='Shared'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='deploytime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Deployment Time'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='display_field',
            field=models.TextField(blank=True, null=True, verbose_name='Column to be displayed'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='flow_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='flow_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Flow Number'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='flowcounter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Flow Count'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='flowlog',
            field=models.BooleanField(default=False, verbose_name='LOG'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='flowobject',
            field=models.TextField(blank=True, null=True, verbose_name='Flow Design'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='formcounter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Form count'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='formobject',
            field=models.TextField(blank=True, null=True, verbose_name='Flow Form Design'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='fp_show',
            field=models.BooleanField(default=False, verbose_name='Show flow status'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='history',
            field=models.BooleanField(default=False, verbose_name='Operation History'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Enable/Disable'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='merge_formobject',
            field=models.TextField(blank=True, null=True, verbose_name='Integrated Form Design'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='mission',
            field=models.BooleanField(default=True, verbose_name='Create Mission'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='parent_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Main flow Number'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='permission',
            field=models.TextField(blank=True, null=True, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='relation',
            field=models.BooleanField(default=False, verbose_name='Show related information'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='search_field',
            field=models.TextField(blank=True, null=True, verbose_name='The field to be queried'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='status_field',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Status Field'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='title_field',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title Field'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='undeploy_flag',
            field=models.BooleanField(default=False, verbose_name='Offline'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='undeploy_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Offline time'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='version',
            field=models.IntegerField(blank=True, null=True, verbose_name='Flow Version'),
        ),
        migrations.AlterField(
            model_name='flowactive',
            name='worklog',
            field=models.BooleanField(default=False, verbose_name='Diary'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='Flow Setting'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='flow_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='flowobject',
            field=models.TextField(blank=True, null=True, verbose_name='Flow Design'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='formobject',
            field=models.TextField(blank=True, null=True, verbose_name='Flow Form Design'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='subflow',
            field=models.TextField(blank=True, null=True, verbose_name='Sub-Flow'),
        ),
        migrations.AlterField(
            model_name='flowworkspace',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='data_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data Number'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='data_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data Serial Number'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='Delete or not'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='file_name',
            field=models.TextField(blank=True, null=True, verbose_name='File name'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='flow_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Flow Number'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='size',
            field=models.IntegerField(blank=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='omdatafiles',
            name='upload_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_omdatefile', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Upload Person'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Create Staff'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='object_flow',
            field=models.UUIDField(blank=True, null=True, verbose_name='Form2 Flow'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='object_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sub-Data Number'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='relation_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Percentage Affected'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='relation_type',
            field=models.TextField(blank=True, null=True, verbose_name='Association Type'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='subject_flow',
            field=models.UUIDField(blank=True, null=True, verbose_name='Main FormFlow'),
        ),
        migrations.AlterField(
            model_name='omdatarelation',
            name='subject_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Master Information Number'),
        ),
        migrations.AlterField(
            model_name='omdataworklog',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='omdataworklog',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_worklog', to=settings.AUTH_USER_MODEL, verbose_name='Creater'),
        ),
        migrations.AlterField(
            model_name='omdataworklog',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='omdataworklog',
            name='data_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data Serial Number'),
        ),
        migrations.AlterField(
            model_name='omdataworklog',
            name='flow_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Flow Number'),
        ),
        migrations.AlterField(
            model_name='omparameter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='omparameter',
            name='group_id',
            field=models.TextField(blank=True, null=True, verbose_name='Group id'),
        ),
        migrations.AlterField(
            model_name='omparameter',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Parameter Name'),
        ),
        migrations.AlterField(
            model_name='omparameter',
            name='shadow',
            field=models.BooleanField(default=False, verbose_name='Whether to mask'),
        ),
        migrations.AlterField(
            model_name='omparameter',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='omparameter',
            name='value',
            field=models.TextField(blank=True, null=True, verbose_name='Parameter Value'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='app_name',
            field=models.CharField(max_length=200, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Close Tag'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='data_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data Number'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='flow_name',
            field=models.CharField(max_length=200, verbose_name='Flow Name'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='level',
            field=models.CharField(default='green', max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='remind',
            field=models.TextField(blank=True, null=True, verbose_name='Reminder'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='type',
            field=models.TextField(default='num', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='sladata',
            name='violation',
            field=models.TextField(blank=True, null=True, verbose_name='Violation'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='advanced',
            field=models.TextField(blank=True, null=True, verbose_name='Advanced Conditions'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='app_name',
            field=models.CharField(max_length=200, verbose_name='App Name'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='flow_name',
            field=models.CharField(max_length=200, verbose_name='Flow Name'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='flow_uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='Flow Number'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='notify_createuser',
            field=models.BooleanField(default=False, verbose_name='Notify Creater'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='notify_group',
            field=models.TextField(blank=True, null=True, verbose_name='Notification Role'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='notify_user',
            field=models.TextField(blank=True, null=True, verbose_name='Notify user'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='remind',
            field=models.TextField(blank=True, null=True, verbose_name='Reminder'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='sla_name',
            field=models.CharField(max_length=200, verbose_name='SLA Name'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='Numerical Measurement Field'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='timer_end',
            field=models.TextField(blank=True, null=True, verbose_name='Time measurement terminated'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='timer_start',
            field=models.TextField(blank=True, null=True, verbose_name='Time measurement start'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='slarule',
            name='violation',
            field=models.TextField(blank=True, null=True, verbose_name='Violation'),
        ),
        migrations.AlterField(
            model_name='workspaceapplication',
            name='active_app_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='corresponding name'),
        ),
        migrations.AlterField(
            model_name='workspaceapplication',
            name='app_attr',
            field=models.CharField(max_length=100, verbose_name='Properties'),
        ),
        migrations.AlterField(
            model_name='workspaceapplication',
            name='language_package',
            field=models.TextField(default='{}', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='workspaceapplication',
            name='updatetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Update time'),
        ),
    ]
