# Generated by Django 3.1.5 on 2021-01-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_uuid', models.UUIDField(blank=True, null=True, verbose_name='流程編號')),
                ('flow_name', models.TextField(blank=True, null=True, verbose_name='流程名稱')),
                ('status', models.TextField(blank=True, null=True, verbose_name='狀態')),
                ('level', models.TextField(blank=True, null=True, verbose_name='燈號')),
                ('title', models.TextField(blank=True, null=True, verbose_name='標題')),
                ('data_no', models.IntegerField(blank=True, null=True, verbose_name='資料編號')),
                ('data_id', models.IntegerField(blank=True, null=True, verbose_name='資料流水號')),
                ('history', models.BooleanField(default=False, verbose_name='歷史資料')),
                ('stop_uuid', models.TextField(blank=True, null=True, verbose_name='關卡')),
                ('stop_chart_text', models.TextField(blank=True, null=True, verbose_name='關卡名稱')),
                ('ticket_createtime', models.DateTimeField(blank=True, null=True, verbose_name='開單時間')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('action', models.TextField(blank=True, null=True, verbose_name='快速操作')),
                ('attachment', models.BooleanField(default=False, verbose_name='附加檔案')),
                ('closed', models.BooleanField(default=False, verbose_name='關單')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用/停用')),
                ('deploy_flag', models.BooleanField(default=True, verbose_name='上架')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
