# Generated by Django 2.2 on 2020-08-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ommission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='deploy_flag',
            field=models.BooleanField(default=True, verbose_name='上架'),
        ),
        migrations.AddField(
            model_name='missions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='啟用/停用'),
        ),
    ]
