# Generated by Django 2.0.13 on 2021-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='名稱')),
                ('value', models.TextField(blank=True, null=True, verbose_name='值')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField(blank=True, null=True, verbose_name='名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='說明')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
