from django.urls import path
from omformflow import views
from django.conf.urls import url

urlpatterns = [
    url(r'^page/flow-app/$', views.flowAppManagePage),
    url(r'^page/flowManagePage/(?P<url>.+)$', views.flowManagePage),
    url(r'^page/workflow-app/$', views.workflowAppManagePage),
    url(r'^page/workflowManagePage/(?P<url>.+)$', views.workflowManagePage),
    url(r'^page/scheduleflowManagePage/$', views.scheduleflowManagePage),
    url(r'^page/flowCreatePage/$', views.flowCreatePage),
    url(r'^page/flowDesignPage/(?P<url>.+)$', views.flowDesignPage),
    url(r'^page/workflowPage/(?P<url>.+)$', views.workflowPage),
    url(r'^page/flowvaluePage/(?P<url>.+)$', views.flowvaluePage),
    path('api/flow-workspace-app/edit/', views.editWorkspaceApplicationAjax, name='editWorkspaceApplicationAjax'),
    path('api/flow-workspace-app/list/', views.listWorkspaceApplicationAjax, name='listWorkspaceApplicationAjax'),
    path('api/flow-workspace-app/deploy/', views.deployWorkspaceApplicationAjax, name='deployWorkspaceApplicationAjax'),
    path('api/flow-workspace-app/export/', views.exportWorkspaceApplicationAjax, name='exportWorkspaceApplicationAjax'),
    path('api/flow-workspace-app/import/', views.importWorkspaceApplicationAjax, name='importWorkspaceApplicationAjax'),
    path('api/flow-workspace/create/', views.createFlowWorkspaceAjax, name='createFlowWorkspaceAjax'),
    path('api/flow-workspace/list/', views.listFlowWorkspaceAjax, name='listFlowWorkspaceAjax'),
    path('api/flow-workspace/update/', views.updateFlowWorkspaceAjax, name='updateFlowWorkspaceAjax'),
    path('api/flow-workspace/load/', views.loadFlowWorkspaceAjax, name='loadFlowWorkspaceAjax'),
    path('api/flow-workspace/delete/', views.deleteFlowWorkspaceAjax, name='deleteFlowWorkspaceAjax'),
    path('api/flow-workspace/copy/', views.copyFlowWorkspaceAjax, name='copyFlowWorkspaceAjax'),
    path('api/flow-workspace-outside/get/', views.getOutsideFlowAjax, name='getOutsideFlowAjax'),
    path('api/flow-workspace-inside/get/', views.getInsideFlowAjax, name='getInsideFlowAjax'),
    path('api/flow-version/list/', views.listFlowVersionAjax, name='listFlowVersionAjax'),
    path('api/flow-active/list/', views.listFlowActiveAjax, name='listFlowActiveAjax'),
    path('api/flow-active/schedule/list/', views.listSchedulerAjax, name='listSchedulerAjax'),
    path('api/flow-active/update/', views.updateFlowActiveAjax, name='updateFlowActiveAjax'),
    path('api/flow-active/schedule/', views.scheduleFlowActiveAjax, name='scheduleFlowActiveAjax'),
    path('api/flow-active/active/', views.activeFlowActiveAjax, name='activeFlowActiveAjax'),
    path('api/flow-active-app/export/', views.exportActiveApplicationAjax, name='exportActiveApplicationAjax'),
    path('api/flow-active-app/undeploy/', views.undeployActiveApplicationAjax, name='undeployActiveApplicationAjax'),
    path('api/flow-active-app/redeploy/', views.redeployActiveApplicationAjax, name='redeployActiveApplicationAjax'),
    path('api/flow-active-app/list/', views.listActiveApplicationAjax, name='listActiveApplicationAjax'),
    path('api/flow-active-display-field/get/', views.getFlowActiveDisplayFieldAjax, name='getFlowActiveDisplayFieldAjax'),
    path('api/schedule/active/', views.activeScheduleAjax, name='activeScheduleAjax'),
    path('api/form-design/load/', views.loadFormDesignAjax, name='loadFormDesignAjax'),
    path('api/flow-display/get/', views.getFlowFieldNameAjax, name='getFlowFieldNameAjax'),
    path('api/flow-name/load/', views.getApplicationFlowNameAjax, name='getApplicationFlowNameAjax'),
    path('api/omdata/edit/', views.editOmDataAjax, name='editOmDataAjax'),
    path('api/omdata/list/', views.listOmDataAjax, name='listOmDataAjax'),
    path('api/omdata/load/', views.loadOmDataAjax, name='loadOmDataAjax'),
    path('api/omdata-file/upload/', views.uploadOmdataFilesAjax, name='uploadOmdataFilesAjax'),
    path('api/omdata-file/list/', views.listOmDataFilesAjax, name='listOmDataFilesAjax'),
    path('api/omdata-history/list/', views.listOmDataHistoryAjax, name='listOmDataHistoryAjax'),
    path('api/flow-value/get/', views.getFlowValueAjax, name='getFlowValueAjax'),
    path('api/flow-value/update/', views.updateFlowValueAjax, name='updateFlowValueAjax'),
    path('api/flow-object/load/', views.loadFlowObjectAjax, name='loadFlowObjectAjax'),
    path('api/cloud-flow/get/', views.getCloudFlowAjax, name='getCloudFlowAjax'),
    ]