# Generated by Django 2.0.13 on 2021-03-14 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='顯示名稱')),
                ('host_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='主機名稱')),
                ('unique_id', models.TextField(max_length=100, verbose_name='主機識別碼')),
                ('os_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='作業系統')),
                ('os_release', models.CharField(blank=True, max_length=100, null=True, verbose_name='作業系統版本1')),
                ('os_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='作業系統版本2')),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP位置')),
                ('access_port', models.CharField(blank=True, max_length=30, null=True, verbose_name='連接阜')),
                ('omflow_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='omflow版本')),
                ('loadbalance', models.BooleanField(default=False, verbose_name='負載平衡')),
                ('level', models.IntegerField(default=1, verbose_name='燈號')),
                ('software', models.TextField(blank=True, null=True, verbose_name='軟體清單')),
                ('hardware', models.TextField(blank=True, null=True, verbose_name='硬體資訊')),
                ('security', models.TextField(blank=True, null=True, verbose_name='api碼')),
                ('updatetime', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CollectorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='群組名稱')),
                ('type', models.TextField(blank=True, null=True, verbose_name='類型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='說明')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='EventManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.TextField(blank=True, null=True, verbose_name='應用程式')),
                ('type', models.TextField(blank=True, null=True, verbose_name='分類')),
                ('title', models.TextField(blank=True, null=True, verbose_name='標題')),
                ('content', models.TextField(blank=True, null=True, verbose_name='內文')),
                ('critical', models.IntegerField(default=1, verbose_name='嚴重等級')),
                ('source', models.TextField(blank=True, null=True, verbose_name='來源')),
                ('source2', models.TextField(blank=True, null=True, verbose_name='來源2')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='開單時間')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('closed', models.BooleanField(default=False, verbose_name='關單標記')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ommonitor.Collector')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='IncidentRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(blank=True, null=True, verbose_name='條件')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LoadBalanceQueueData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.TextField(blank=True, null=True, verbose_name='佇列編號')),
                ('module_name', models.TextField(blank=True, null=True, verbose_name='模組名稱')),
                ('method_name', models.TextField(blank=True, null=True, verbose_name='方法名稱')),
                ('input_param', models.TextField(blank=True, null=True, verbose_name='輸入參數')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonitorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200)),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('active_app_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='對應名稱')),
                ('app_attr', models.CharField(max_length=100, verbose_name='屬性')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('OmMonitor_Manage', '資料收集管理'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MonitorFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.TextField(blank=True, null=True, verbose_name='資料表編號')),
                ('flow_name', models.CharField(max_length=200, verbose_name='名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='說明')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('formobject', models.TextField(blank=True, null=True, verbose_name='流程表單設計')),
                ('flowobject', models.TextField(blank=True, null=True, verbose_name='流程設計')),
                ('config', models.TextField(blank=True, null=True, verbose_name='流程設定')),
                ('subflow', models.TextField(blank=True, null=True, verbose_name='子流程')),
                ('attr', models.TextField(blank=True, null=True, verbose_name='屬性')),
                ('type', models.TextField(blank=True, null=True, verbose_name='分類')),
                ('os_type', models.TextField(blank=True, null=True, verbose_name='作業系統')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('schedule', models.TextField(blank=True, null=True, verbose_name='排程')),
                ('event_rule', models.TextField(blank=True, null=True, verbose_name='事件規則')),
                ('python_package', models.BooleanField(default=False, verbose_name='套件')),
                ('history', models.BooleanField(default=False, verbose_name='歷史資料')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flow_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ommonitor.MonitorApplication')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PolicyCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.TextField(blank=True, null=True, verbose_name='資料表編號')),
                ('policy_version', models.IntegerField(blank=True, null=True, verbose_name='版本')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ommonitor.Collector')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ommonitor.MonitorFlow')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='collector',
            name='nodegroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ommonitor.CollectorGroup'),
        ),
        migrations.AddField(
            model_name='collector',
            name='policys',
            field=models.ManyToManyField(through='ommonitor.PolicyCollector', to='ommonitor.MonitorFlow'),
        ),
    ]
