"""
Django settings for omflow project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from pytz import common_timezones
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '1han1v%@fd0#e40#tm0z!g2twgo3+!gf9-kr3--1v5)_bkfv4q'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
TEMPLATE_DEBUG = DEBUG

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
     #default
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #local components
    'omuser',
    'ommessage',
    'omformflow',
    'omflow',
    'omdashboard',
    'omformmodel',
    'omservice',
    'ommission',
   
]
AUTH_USER_MODEL = 'omuser.OmUser'
LOGIN_REDIRECT_URL = '/home/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    
]

ROOT_URLCONF = 'omflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.i18n',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.csrf',
            ],
        },
    },
]

WSGI_APPLICATION = 'omflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#PASSWORD_RESET_TIMEOUT_DAYS = 1

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = [

    ("en", "English"),("zh-hant", "Traditional_Chinese"),("zh-hans", "Simplified_Chinese"),("ja", "Japanese"),("ar","Arabic")
]


LANGUAGE_CODE = 'ar'
#TIME_ZONE = 'Africa/Cairo'
TIME_ZONES = [(tz, tz) for tz in common_timezones]
DATE_FORMAT = '%Y-%m-%d'
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATETIME_INPUT_FORMATS = '%Y-%m-%d %H:%M:%S'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_AGE = 3600

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
FILE_UPLOAD_TEMP_DIR = BASE_DIR
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800   


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


#STATICFILES_FINDERS = (
#    'django.contrib.staticfiles.finders.FileSystemFinder',
#    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#for prifex langages
STATIC_URL = '/static/'

# static url Mapping folder
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'staticfiles'),
    #os.path.join(BASE_DIR, 'omuser', 'staticfiles'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = os.path.join(BASE_DIR, '..', 'static')

LOG_DIR = os.path.join(BASE_DIR, 'logs')
    
LOG_LEVEL = 'ERROR'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  
    'formatters': { 
        'simple': {
            'format': '[%(asctime)s] - %(levelname)-8s - %(message)s',
            'datefmt': DATETIME_FORMAT,
        },     
    },
    "filters": {   
        "infofilter": {  
          "()": "omflow.syscom.default_logger.LowLevelFilter",
          "level": 20
        },
        "warnfilter": {  
          "()": "omflow.syscom.default_logger.HighLevelFilter",
          "level": 30
        }
    },
    'handlers': {  
        'consoleInfo': { 
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            "filters": ["infofilter"]
        },
        'consoleError': { 
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            "stream": "ext://sys.stdout",
            "filters": ["warnfilter"]
        },
        'omlogfile': { 
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'omflow.log'),
            'encoding':'utf-8',
            'formatter': 'simple',
            'when': 'midnight', 
            'backupCount': 10,
            'delay': True
       },
        'djangolog': { 
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'djangolog.log'),
            'encoding':'utf-8',
            'formatter': 'simple',
            'when': 'midnight', 
            'backupCount': 10, 
            'delay': True
       },
    },
    'loggers': { 
        'django': { 
            'handlers': ['consoleInfo','consoleError','djangolog'],
            'level': LOG_LEVEL, 
            'propagate': False 
        },
        'omflowlog': { 
            'handlers': ['omlogfile'],
            'level': LOG_LEVEL, 
            'propagate': False 
        },
    },
      
}

DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3","NAME": os.path.join(BASE_DIR, "db.omflow"),"OPTIONS": {"timeout": 300,}}}
#omflow type(server/collector)
OMFLOW_TYPE = "server"
#local info
LOCAL_IP = ""
LOCAL_PORT = ""
UNIQUE_ID = ""
#server info
SERVER_IP = ""
SERVER_PORT = ""
#python.exe filepath
PYTHON_PATH = ""