"""
Django settings for omflow project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r&94@o%)q8s-=gmxw@8a9o5161%90&2jo$0*&a&57*5$rx)@ar'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'omuser',
    'ommessage',
    'omformflow',
    'omflow',
    'omdashboard',
    'omformmodel',
    'omservice',
    'ommission',
    #'omldap',
    #default
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
AUTH_USER_MODEL = 'omuser.OmUser'
LOGIN_REDIRECT_URL = '/home/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'omflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'omflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.omflow'),
        'OPTIONS': {
            'timeout': 300,
            }
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

LANGUAGES = [
#     ('en', "英文"),
    ('zh-hant', "繁體中文"),
]


LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'
DATE_FORMAT = '%Y-%m-%d'
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DATETIME_INPUT_FORMATS = '%Y-%m-%d %H:%M:%S'

USE_I18N = True

USE_L10N = False

#USE_TZ = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# SESSION_COOKIE_AGE = 3600
# 如果開啟 TimeOut 自登入開始計時，時間到會強制登出，任何操作皆不會重新計時

MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
FILE_UPLOAD_TEMP_DIR = BASE_DIR
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800   


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
#定義 static url Mapping 的 folder
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'staticfiles'),
    os.path.join(BASE_DIR, 'omuser', 'staticfiles'),
)
#佈署時可透過指令將staticfiles_dirs目錄下的檔案同步到指定的資料夾
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

LOG_DIR = os.path.join(BASE_DIR, 'logs')
LOG_LEVEL = 'INFO'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  #如果值為False則對已存在的loggers保持啟動狀態
    'formatters': { #format格式
        'simple': {
            'format': '[%(asctime)s] - %(levelname)-8s - %(message)s',
            'datefmt': DATETIME_FORMAT,
        },     
    },
    "filters": {   
        "infofilter": {  #LOG等級在INFO以下印出STDERR
          "()": "omflow.syscom.default_logger.LowLevelFilter",
          "level": 20
        },
        "warnfilter": {  #LOG等級在WARN以下印出STDOUT
          "()": "omflow.syscom.default_logger.HighLevelFilter",
          "level": 30
        }
    },
    'handlers': {  #處理器配置
        'consoleInfo': {  #INFO以下處理器 
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            "filters": ["infofilter"]
        },
        'consoleError': { #WARNING以上處理器
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            "stream": "ext://sys.stdout",
            "filters": ["warnfilter"]
        },
        'omlogfile': { #OMFLOWLOG 檔案配置
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'omflow.log'),
            'encoding':'utf-8',
            'formatter': 'simple',
            'when': 'midnight',  #以天來做備份
            'backupCount': 10, #備份10個LOG檔案
            'delay': True
       },
        'djangolog': { #DJANGO 檔案配置
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'djangolog.log'),
            'encoding':'utf-8',
            'formatter': 'simple',
            'when': 'midnight', #以天來做備份
            'backupCount': 10, #備份10個LOG檔案
            'delay': True
       },
    },
    'loggers': { #設置Logger收集器
        'django': { # Console上呈現於所有資訊，記錄到Djangolog檔案
            'handlers': ['consoleInfo','consoleError','djangolog'],
            'level': LOG_LEVEL, #設定LOG等級
            'propagate': False 
        },
        'omflowlog': { #儲存客製log訊息
            'handlers': ['omlogfile'],
            'level': LOG_LEVEL, #設定LOG等級
            'propagate': False 
        },
    },
      
}

